# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'media_miner.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys, math
from PyQt5 import QtCore, QtGui, QtWidgets



class MediaMiner(QtWidgets.QMainWindow):
    
    def __init__(self, parent= None):
        super().__init__(parent)
        
        _translate = QtCore.QCoreApplication.translate
         
        # Main Window & Central Widget
        self.setObjectName("MainWindow")
        self.resize(700, 350)
        self.setMinimumSize(QtCore.QSize(400, 200))
        self.setMaximumSize(QtCore.QSize(700, 350))
        self.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.setIconSize(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        
        self._resizing = False
        
        # Media Type Selector
        self.media_type_selector = QtWidgets.QComboBox(self.centralwidget)
        self.media_type_selector.setGeometry(QtCore.QRect(10, 10, 200, 25))
        self.media_type_selector.setMaxVisibleItems(3)
        self.media_type_selector.setObjectName("media_type_selector")
        
        
        # URL Line Edit + Label
        self.url_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.url_line_edit.setGeometry(QtCore.QRect(50, 50, 325, 25))
        self.url_line_edit.setObjectName("url_line_edit")


        self.URL_label = QtWidgets.QLabel(self.centralwidget)
        self.URL_label.setGeometry(QtCore.QRect(10, 50, 25, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.URL_label.setFont(font)
        self.URL_label.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.URL_label.setObjectName("URL_label")
        self.URL_label.setText(_translate("MainWindow", "URL:"))
        
        
        # Open Folder Button
        self.folder_button = QtWidgets.QPushButton(self.centralwidget)
        self.folder_button.setGeometry(QtCore.QRect(10, 145, 65, 20))
        self.folder_button.setObjectName("folder_button")
        self.folder_button.setText(_translate("MainWindow", "Open Folder"))
        
        
        # Run Scrape Button
        self.run_button = QtWidgets.QPushButton(self.centralwidget)
        self.run_button.setGeometry(QtCore.QRect(325, 145, 65, 20))
        self.run_button.setObjectName("run_button")
        self.run_button.setText(_translate("MainWindow", "Run Scrape"))
        
        
        # Status Bar
        self.setCentralWidget(self.centralwidget)
        self.status_bar = QtWidgets.QStatusBar(self)
        self.status_bar.setObjectName("status_bar")
        self.setStatusBar(self.status_bar)

        # self.retranslateUi(self)
        self.media_type_selector.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(self)
    
    # def resizeEvent(self, event):
        # if self._resizing:
        #     return
        # self._resizing = True
        # aspect = 2.0 # width / height (change to your desired ratio)
        # w = event.size().width()
        # h = max(1, int(w / aspect))
        # self.resize(w, h)
        # self._resizing = False
        # super().resizeEvent(event)
        
    def resizeEvent(self, event):
        width = int(math.floor(event.size().width()))
        height = int(math.floor(event.size().height()))
        self.media_type_selector.setGeometry(QtCore.QRect(int(math.floor(width * 10/400)), int(math.floor(height * 10/200)), int(math.floor(width / 2)), int(math.floor(height / 8))))
        self.URL_label.setGeometry(QtCore.QRect(int(math.floor(width * 10/400)), int(math.floor(height * 50/200)), int(math.floor(width / 8)), int(math.floor(height / 8))))
        self.url_line_edit.setGeometry(QtCore.QRect(int(math.floor(width * 60 / 400)), int(math.floor(height * 50/200)), int(math.floor(width - (width * 70 / 400))), int(math.floor(height / 8))))
        self.folder_button.setGeometry(QtCore.QRect(int(math.floor(width * 10/400)), int(math.floor(height * 145/200)), int(math.floor(width / 4)), int(math.floor(height / 8))))
        self.run_button.setGeometry(QtCore.QRect(int(math.floor(width - (width * 11 / 40))), int(math.floor(height * 145/200)), int(math.floor(width / 4)), int(math.floor(height / 8))))
        
        print(int(math.floor(width - (width * 60 / 400))))
        self.status_bar.showMessage(f"Window resized to: {event.size().width()} x {event.size().height()}")
    # def retranslateUi(self, MainWindow):
    #     _translate = QtCore.QCoreApplication.translate
        # MainWindow.setWindowTitle(_translate("MainWindow", "MediaMiner"))
        # self.URL_label.setText(_translate("MainWindow", "URL"))
        # self.folder_button.setText(_translate("MainWindow", "Open Folder"))
        # self.run_button.setText(_translate("MainWindow", "Run Scrape"))
        
        # self.MainWindow.resize(x, y)
                
        # print(f"Window resized to: {x} x {y}")
        # self.status_bar.showMessage(f"Window resized to: {x} x {y}")
  

app = QtWidgets.QApplication(sys.argv)
MM = MediaMiner()
MM.show()
sys.exit(app.exec_())