# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'media_miner.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 200)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setIconSize(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.media_type_selector = QtWidgets.QComboBox(self.centralwidget)
        self.media_type_selector.setGeometry(QtCore.QRect(10, 10, 200, 25))
        self.media_type_selector.setMaxVisibleItems(3)
        self.media_type_selector.setObjectName("media_type_selector")
        self.url_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.url_line_edit.setGeometry(QtCore.QRect(50, 50, 325, 25))
        self.url_line_edit.setObjectName("url_line_edit")
        self.URL_label = QtWidgets.QLabel(self.centralwidget)
        self.URL_label.setGeometry(QtCore.QRect(10, 50, 25, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.URL_label.setFont(font)
        self.URL_label.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.URL_label.setObjectName("URL_label")
        self.folder_button = QtWidgets.QPushButton(self.centralwidget)
        self.folder_button.setGeometry(QtCore.QRect(10, 145, 65, 20))
        self.folder_button.setObjectName("folder_button")
        self.run_button = QtWidgets.QPushButton(self.centralwidget)
        self.run_button.setGeometry(QtCore.QRect(325, 145, 65, 20))
        self.run_button.setObjectName("run_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.media_type_selector.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MediaMiner"))
        self.URL_label.setText(_translate("MainWindow", "URL"))
        self.folder_button.setText(_translate("MainWindow", "Open Folder"))
        self.run_button.setText(_translate("MainWindow", "Run Scrape"))
