# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'media_miner.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import os, sys, math
import video_scrapper
from PyQt5.QtGui import *
from PyQt5.QtCore import *
from PyQt5.QtWidgets import *

class customnLabel(QLabel):
        
    def __init__(self, parent):
        super().__init__(parent)
        self.parent = parent
        
        self.setText("   MediaMiner")
        self.setStyleSheet("background-color: #666666; border:none;")
        
        # Control Buttons
        self.minimize_button = QPushButton(self)
        self.minimize_button.setGeometry(350, 0, 25, 25)
        self.minimize_button.clicked.connect(self.parent.showMinimized)
        self.minimize_button.enterEvent = self.enterHoverEvent
        self.minimize_button.leaveEvent = self.leaveHoverEvent
        
        minimize_icon = QIcon('./src/minus.png')
        self.minimize_button.setIcon(minimize_icon)
        self.minimize_button.setStyleSheet("""
            QPushButton {                               
                border: none;
            }
            QPushButton:hover {
                background-color: #AAAAAA;
            }
                                           """)
        
        self.close_button = QPushButton(self)
        self.close_button.setGeometry(375, 0, 25, 25)
        self.close_button.clicked.connect(self.parent.close)
        self.close_button.enterEvent = self.enterHoverEvent
        self.close_button.leaveEvent = self.leaveHoverEvent
        self.close_button.setStyleSheet("""
            QPushButton {                               
                border: none;
            }
            QPushButton:hover {
                background-color: #AAAAAA;
            }
                                           """)
        close_icon = QIcon('./src/close.png')
        self.close_button.setIcon(close_icon)
        
    def enterHoverEvent(self, e):
        QApplication.setOverrideCursor(QCursor(Qt.PointingHandCursor))
        
    def leaveHoverEvent(self, e):
        QApplication.setOverrideCursor(QCursor(Qt.ArrowCursor))

    def mousePressEvent(self, e):
        if e.button() == Qt.LeftButton:
            if self.parent.press_control == 0:
                self.pos = e.pos()
                self.main_pos = self.parent.pos()
        super().mousePressEvent(e)
    def mouseMoveEvent(self, e):
        if self.parent.cursor().shape() == Qt.ArrowCursor:
            self.last_pos = e.pos() - self.pos
            self.main_pos += self.last_pos
            self.parent.move(self.main_pos)
        super(customnLabel, self).mouseMoveEvent(e)

    # def mouseReleaseEvent(self, event):
    #     if event.button() == QtCore.Qt.LeftButton:
    #         self._resizing = False

class MediaMiner(QMainWindow):
    
    def __init__(self, parent= None):
        super().__init__(parent)
        
        _translate = QCoreApplication.translate
         
        # Main Window & Central Widget
        self.setObjectName("MainWindow")
        # self.resize(700, 350)
        self.setWindowTitle("MediaMiner")
        self.setFixedSize(400,225)
        self.setLayoutDirection(Qt.LeftToRight)
        self.setIconSize(QSize(0, 0))
        self.press_control = 0
        self.central_widget = QWidget(self)
        self.central_widget.setObjectName("central_widget")
        
        self.setStyleSheet("""
        background-color: #888888;
        color: #FFFFFF;
                           """)
        
        font = QFont()
        
        
        self.setWindowFlags(self.windowFlags() | Qt.FramelessWindowHint)
        self.topMenu = customnLabel(self)
        self.topMenu.setGeometry(0, 0, 400, 25)
        
        
        self._resizing = False
        
        # Menu Buttons
        menu_button = [10, 35, 127, 25]
        gap = 0

        # self.backdrop = QWidget(self.central_widget)
        # self.backdrop.setGeometry(QRect(
        #     menu_button[0],
        #     menu_button[1],
        #     (menu_button[2] + gap * 2) * 3 - gap * 2,
        #     menu_button[3]
        # ))
        # self.backdrop.setStyleSheet("background-color: #999999; border: none;")
        # self.backdrop.lower()
        
        self.video_button = QPushButton(self.central_widget)
        self.video_button.setGeometry(QRect(menu_button[0], menu_button[1], menu_button[2], menu_button[3]))
        self.video_button.setObjectName("video_button")
        font.setPointSize(8)
        self.video_button.setFont(font)
        self.video_button.setText(_translate("MainWindow", "Video"))
        self.video_button.clicked.connect(lambda: self.toggle_media_type("Video"))
        self.video_button.setStyleSheet("""
            QPushButton {
                border:none;
                background-color: #999999;
                padding-right: 2px solid #FF0000;
            }
            QPushButton:hover {
                background-color: #AAAAAA;
                padding-right: 2px solid #AAAAAA;
            }
                                         """)
        
        self.comic_button = QPushButton(self.central_widget)
        self.comic_button.setGeometry(QRect(menu_button[0] + menu_button[2] + (gap * 2), menu_button[1], menu_button[2], menu_button[3]))
        self.comic_button.setObjectName("comic_button")
        font.setPointSize(8)
        self.comic_button.setFont(font)
        self.comic_button.setText(_translate("MainWindow", "Comic"))
        self.comic_button.clicked.connect(lambda: self.toggle_media_type("Comic"))
        self.comic_button.setStyleSheet("""
            QPushButton {
                border:none;
                background-color: #999999;
                padding-left: 2px solid #999999;
                padding-right: 2px solid #999999;
            }
            QPushButton:hover {
                background-color: #AAAAAA;
                padding-left: 2px solid #AAAAAA;
                padding-right: 2px solid #AAAAAA;
            }
                                         """)
        
        self.lit_button = QPushButton(self.central_widget)
        self.lit_button.setGeometry(QRect(menu_button[0] + (menu_button[2] + (gap * 2)) * 2, menu_button[1], menu_button[2], menu_button[3]))
        self.lit_button.setObjectName("lit_button")
        font.setPointSize(8)
        self.lit_button.setFont(font)
        self.lit_button.setText(_translate("MainWindow", "Literature"))
        self.lit_button.clicked.connect(lambda: self.toggle_media_type("Literature"))
        self.lit_button.setStyleSheet("""
            QPushButton {
                border:none;
                background-color: #999999;
                padding-left: 2px solid #999999;
            }
            QPushButton:hover {
                background-color: #AAAAAA;
                padding-left: 2px solid #AAAAAA;
            }
                                         """)
        print(menu_button[0] + (menu_button[2] + 4) * 2 + menu_button[2])
        print(menu_button[0] + menu_button[2] + (gap * 2))
        print(menu_button[0] + (menu_button[2] + (gap * 2)) * 2)
        
        # Media Type Selector
        # self.media_type_selector = QComboBox(self.central_widget)
        # self.media_type_selector.setGeometry(QRect(10, 35, 200, 25))
        # self.media_type_selector.setMaxVisibleItems(3)
        # self.media_type_selector.setObjectName("media_type_selector")
        
        # icon_video = QIcon("./src/video-camera.png")
        # self.media_type_selector.addItem(icon_video, "Video")
        # icon_comics = QIcon("./src/comic-book.png")
        # self.media_type_selector.addItem(icon_comics, "Comics")
        # icon_literature = QIcon("./src/open-book.png")
        # self.media_type_selector.addItem(icon_literature, "Literature")
        
        # self.media_type_selector.setStyleSheet("""
        #         QComboBox {
        #             selection-background-color: #888888;
        #         }
        #         QComboBox::hover {
        #             selection-background-color: #888888;
        #         }
        #                                        """)
        
        # URL Line Edit + Label
        self.url_line_edit = QLineEdit(self.central_widget)
        self.url_line_edit.setGeometry(QRect(60, 115, 330, 25))
        self.url_line_edit.setObjectName("url_line_edit")
        self.url_line_edit.setStyleSheet("""
                QLineEdit {
                    border: none;
                    border-bottom: 2px solid #FFFFFF; 
                    selection-background-color: #aaaaaa;
                    color: #FFFFFF;
                    selection-color: #000000;
                }
                                         """)


        self.URL_label = QLabel(self.central_widget)
        self.URL_label.setGeometry(QRect(10, 115, 50, 25))
        font.setPointSize(10)
        self.URL_label.setFont(font)
        self.URL_label.setCursor(QCursor(Qt.ArrowCursor))
        self.URL_label.setObjectName("URL_label")
        self.URL_label.setText(_translate("MainWindow", "URL:"))
        
        
        # Open Folder Button
        self.folder_button = QPushButton(self.central_widget)
        self.folder_button.setGeometry(QRect(10, 170, 100, 25))
        self.folder_button.setObjectName("folder_button")
        font.setPointSize(8)
        self.folder_button.setFont(font)
        self.folder_button.setText(_translate("MainWindow", "Open Folder"))
        self.folder_button.clicked.connect(self.open_folder)
        self.folder_button.setStyleSheet("""
            QPushButton {
                border:none;
                background-color: #999999;
            }
            QPushButton:hover {
                background-color: #AAAAAA;
            }
                                         """)
        
        
        # Run Scrape Button
        self.run_button = QPushButton(self.central_widget)
        self.run_button.setGeometry(QRect(290, 170, 100, 25))
        self.run_button.setObjectName("run_button")
        font.setPointSize(8)
        self.run_button.setFont(font)
        self.run_button.setText(_translate("MainWindow", "Run Scrape"))
        self.run_button.clicked.connect(self.run_scrape)
        self.run_button.setStyleSheet("""
            QPushButton {
                border:none;
                background-color: #999999;
            }
            QPushButton:hover {
                background-color: #AAAAAA;
            }
                                      """)
        
        
        # Status Bar
        self.setCentralWidget(self.central_widget)
        self.status_bar = QStatusBar(self)
        self.status_bar.setObjectName("status_bar")
        
        self.status_bar.setAutoFillBackground(True)
        self.status_bar.setStyleSheet("""
        border:none;
        background-color: #202020;
        color: #B09C00;
                                      """)
        self.status_bar.setSizeGripEnabled(False)
        self.setStatusBar(self.status_bar)

        # self.retranslateUi(self)
        # self.media_type_selector.setCurrentIndex(-1)
        QMetaObject.connectSlotsByName(self)
    
    def toggle_media_type(self, media_type):
        if media_type == "Video":
            self.status_bar.showMessage("Media type set to Video")
            self.video_button.setStyleSheet("""
                QPushButton {
                    border:none;
                    background-color: #AAAAAA;
                    padding-right: 2px solid #AAAAAA;
                }
                                            """)
            self.comic_button.setStyleSheet("""
                QPushButton {
                    border:none;
                    background-color: #999999;
                    padding-left: 2px solid #999999;
                    padding-right: 2px solid #999999;
                }
                QPushButton:hover {
                    background-color: #AAAAAA;
                    padding-left: 2px solid #AAAAAA;
                    padding-right: 2px solid #AAAAAA;
                }
                                            """)
            self.lit_button.setStyleSheet("""
                QPushButton {
                    border:none;
                    background-color: #999999;
                    padding-left: 2px solid #999999;
                }
                QPushButton:hover {
                    background-color: #AAAAAA;
                    padding-left: 2px solid #AAAAAA;
                }
                                            """)
        elif media_type == "Comic":
            self.status_bar.showMessage("Media type set to Comic")
            self.comic_button.setStyleSheet("""
                QPushButton {
                    border:none;
                    background-color: #AAAAAA;
                    padding-left: 2px solid #AAAAAA;
                    padding-right: 2px solid #AAAAAA;
                }
                                            """)
            self.video_button.setStyleSheet("""
                QPushButton {
                    border:none;
                    background-color: #999999;
                    padding-right: 2px solid #999999;
                }
                QPushButton:hover {
                    background-color: #AAAAAA;
                    padding-right: 2px solid #AAAAAA;
                }
                                            """)
            self.lit_button.setStyleSheet("""
                QPushButton {
                    border:none;
                    background-color: #999999;
                    padding-left: 2px solid #999999;
                }
                QPushButton:hover {
                    background-color: #AAAAAA;
                    padding-left: 2px solid #AAAAAA;
                }
                                            """)
        elif media_type == "Literature":
            self.status_bar.showMessage("Media type set to Literature")
            self.lit_button.setStyleSheet("""
                QPushButton {
                    border:none;
                    background-color: #AAAAAA;
                    padding-left: 2px solid #AAAAAA;
                }
                                            """)
            self.comic_button.setStyleSheet("""
                QPushButton {
                    border:none;
                    background-color: #999999;
                    padding-left: 2px solid #999999;
                    padding-right: 2px solid #999999;
                }
                QPushButton:hover {
                    background-color: #AAAAAA;
                    padding-left: 2px solid #AAAAAA;
                    padding-right: 2px solid #AAAAAA;
                }
                                            """)
            self.video_button.setStyleSheet("""
                QPushButton {
                    border:none;
                    background-color: #999999;
                    padding-right: 2px solid #999999;
                }
                QPushButton:hover {
                    background-color: #AAAAAA;
                    padding-right: 2px solid #AAAAAA;
                }
                                            """)
        pass
        
    
    def open_folder(self):
        folder_path = "C:/Users/t2tra/Documents/K20/_"
        os.startfile(folder_path)
    
    def run_scrape(self):
        # selected_media_type = self.media_type_selector.currentText()
        selected_media_type = "test"
        url = self.url_line_edit.text()
        
        if not selected_media_type:
            self.status_bar.showMessage("Please select a media type.")
            # print("Please select a media type.")
            return
        if not url:
            self.status_bar.showMessage("Please enter a URL.")
            # print("Please enter a URL.")
            return
        self.status_bar.showMessage(f"Scraping {selected_media_type} from {url}...")
        
        if selected_media_type == "Video":
            video_scrapper(url)
            
        elif selected_media_type == "Comics":
            print(f"Starting comics scrape for URL: {url}")
        elif selected_media_type == "Literature":
            print(f"Starting literature scrape for URL: {url}")
        
    
    
    
    
    
        
    def eventFilter(self, obj, e):
        #hovermoveevent
        if e.type() == 129:
            if self.press_control == 0:
                self.pos_control(e)#cursor position control for cursor shape setup

        #mousepressevent
        if e.type() == 2:
            self.press_control = 1
            self.origin = self.mapToGlobal(e.pos())
            self.ori_geo = self.geometry()

        #mousereleaseevent
        if e.type() == 3:

            self.press_control = 0
            self.pos_control(e)
        
        #mosuemoveevent
        if e.type() == 5:
            if self.cursor().shape() != Qt.ArrowCursor:
                self.resizing(self.origin, e, self.ori_geo, self.value)

        return True

    def pos_control(self, e):
        rect = self.rect()
        top_left = rect.topLeft()
        top_right = rect.topRight()
        bottom_left = rect.bottomLeft()
        bottom_right = rect.bottomRight()
        pos = e.pos()

        #top catch
        if pos in QRect(QPoint(top_left.x()+5,top_left.y()), QPoint(top_right.x()-5,top_right.y()+5)):
            self.setCursor(Qt.SizeVerCursor)
            self.value = 1

        #bottom catch
        elif pos in QRect(QPoint(bottom_left.x()+5,bottom_left.y()), QPoint(bottom_right.x()-5,bottom_right.y()-5)):
            self.setCursor(Qt.SizeVerCursor)
            self.value = 2
        
        #right catch
        elif pos in QRect(QPoint(top_right.x()-5,top_right.y()+5), QPoint(bottom_right.x(),bottom_right.y()-5)):
            self.setCursor(Qt.SizeHorCursor)
            self.value = 3

        #left catch
        elif pos in QRect(QPoint(top_left.x()+5,top_left.y()+5), QPoint(bottom_left.x(),bottom_left.y()-5)):
            self.setCursor(Qt.SizeHorCursor)
            self.value = 4

        #top_right catch
        elif pos in QRect(QPoint(top_right.x(),top_right.y()), QPoint(top_right.x()-5,top_right.y()+5)):
            self.setCursor(Qt.SizeBDiagCursor)
            self.value = 5

        #botom_left catch
        elif pos in QRect(QPoint(bottom_left.x(),bottom_left.y()), QPoint(bottom_left.x()+5,bottom_left.y()-5)):
            self.setCursor(Qt.SizeBDiagCursor)
            self.value = 6

        #top_left catch
        elif pos in QRect(QPoint(top_left.x(),top_left.y()), QPoint(top_left.x()+5,top_left.y()+5)):
            self.setCursor(Qt.SizeFDiagCursor)
            self.value = 7

        #bottom_right catch
        elif pos in QRect(QPoint(bottom_right.x(),bottom_right.y()), QPoint(bottom_right.x()-5,bottom_right.y()-5)):
            self.setCursor(Qt.SizeFDiagCursor)
            self.value = 8
        
        #default
        else:
            self.setCursor(Qt.ArrowCursor)       

    def resizing(self, ori, e, geo, value):    
        #top_resize
        if self.value == 1:
            last = self.mapToGlobal(e.pos())-ori
            first = geo.height()
            first -= last.y()
            Y = geo.y()
            Y += last.y()

            if first > self.minimumHeight():
                self.setGeometry(geo.x(), Y, geo.width(), first)                    
        
        #bottom_resize
        if self.value == 2:
            last = self.mapToGlobal(e.pos())-ori
            first = geo.height()
            first += last.y()
            self.resize(geo.width(), first)

        #right_resize
        if self.value == 3:
            last = self.mapToGlobal(e.pos())-ori
            first = geo.width()
            first += last.x()
            self.resize(first, geo.height())

        #left_resize
        if self.value == 4:
            last = self.mapToGlobal(e.pos())-ori
            first = geo.width()
            first -= last.x()
            X = geo.x()
            X += last.x()

            if first > self.minimumWidth():
                self.setGeometry(X, geo.y(), first, geo.height())

        #top_right_resize
        if self.value == 5:
            last = self.mapToGlobal(e.pos())-ori
            first_width = geo.width()
            first_height = geo.height()
            first_Y = geo.y()
            first_width += last.x()
            first_height -= last.y()
            first_Y += last.y()
                
            if first_height > self.minimumHeight():
                self.setGeometry(geo.x(), first_Y, first_width, first_height)

        #bottom_right_resize
        if self.value == 6:
            last = self.mapToGlobal(e.pos())-ori
            first_width = geo.width()
            first_height = geo.height()
            first_X = geo.x()
            first_width -= last.x()
            first_height += last.y()
            first_X += last.x()
                
            if first_width > self.minimumWidth():
                self.setGeometry(first_X, geo.y(), first_width, first_height)

        #top_left_resize
        if self.value == 7:
            last = self.mapToGlobal(e.pos())-ori
            first_width = geo.width()
            first_height = geo.height()
            first_X = geo.x()
            first_Y = geo.y()
            first_width -= last.x()
            first_height -= last.y()
            first_X += last.x()
            first_Y += last.y()
                
            if first_height > self.minimumHeight() and first_width > self.minimumWidth():
                self.setGeometry(first_X, first_Y, first_width, first_height)

        #bottom_right_resize
        if self.value == 8:
            last = self.mapToGlobal(e.pos())-ori
            first_width = geo.width()
            first_height = geo.height()
            first_width += last.x()
            first_height += last.y()                    
            
            self.setGeometry(geo.x(), geo.y(), first_width, first_height)           
        
    # def resizeEvent(self, event):
    #     width = int(math.floor(event.size().width()))
    #     height = int(math.floor(event.size().height()))
    #     self.media_type_selector.setGeometry(QtCore.QRect(int(math.floor(width * 10/400)), int(math.floor(height * 10/200)), int(math.floor(width / 2)), int(math.floor(height / 8))))
    #     self.URL_label.setGeometry(QtCore.QRect(int(math.floor(width * 10/400)), int(math.floor(height * 50/200)), int(math.floor(width / 8)), int(math.floor(height / 8))))
    #     self.url_line_edit.setGeometry(QtCore.QRect(int(math.floor(width * 60 / 400)), int(math.floor(height * 50/200)), int(math.floor(width - (width * 70 / 400))), int(math.floor(height / 8))))
    #     self.folder_button.setGeometry(QtCore.QRect(int(math.floor(width * 10/400)), int(math.floor(height * 145/200)), int(math.floor(width / 4)), int(math.floor(height / 8))))
    #     self.run_button.setGeometry(QtCore.QRect(int(math.floor(width - (width * 11 / 40))), int(math.floor(height * 145/200)), int(math.floor(width / 4)), int(math.floor(height / 8))))
        
    #     self.status_bar.showMessage(f"Window resized to: {event.size().width()} x {event.size().height()}")
    #     print(f"Window resized to: {event.size().width()} x {event.size().height()}")

  
os.environ["QT_AUTO_SCREEN_SCALE_FACTOR"] = "1"
app = QApplication(sys.argv)
MM = MediaMiner()
MM.show()
sys.exit(app.exec_())